name: Publish
# This workflow is triggered on pushes to the repository.
on: release

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: actions/bin/filter@master
        with:
          args: tag
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Publish
        uses: actions/npm@master
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          args: publish
